# _central_element.sage - is the parity lemma really the CENTRE acting?
#   Claim to test: advancing the Wilson line by one unit of alpha_2 (i.e. t -> -t on the
#   generating variable) acts on the weight system exactly as the central element -I of SU(4).
#   Z(SU(4)) = {zeta I : zeta^4 = 1}; on an irrep of n-ality |lambda| mod 4 the element zeta I
#   acts as zeta^|lambda|. So -I acts as (-1)^|lambda| -- which is precisely the factor in
#   D(-t) = (-1)^|lambda| D(t). If this holds, the lemma is not a Schur coincidence: it is the
#   centre, and the centre charge governs the potential because a half-period of the Wilson
#   line IS a central gauge transformation.
#   Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)
A3 = WeylCharacterRing("A3", style="coroots")

print("1) -I lies in SU(4):  det(-I) =", (-identity_matrix(4)).det())
print("2) -I is central of order 2 inside Z(SU(4)) = Z4 generated by i*I:")
print("     (i*I)^2 =", (I*identity_matrix(CC,4))^2 == -identity_matrix(CC,4))

print("\n3) On an irrep of n-ality k, the central element zeta*I acts as zeta^k.")
print("   For zeta = -1 this is (-1)^k = (-1)^(a+2b+3c).  Check against the weights:")
print("   %-10s %-8s %-10s %-12s %s" % ("(a,b,c)","boxes","n-ality","(-1)^boxes","-I acts as"))
bad = 0
for L in [(0,1,0),(1,0,0),(4,0,0),(0,2,1),(1,1,2),(0,3,1),(1,0,1),(2,1,2),(1,1,1)]:
    boxes = L[0] + 2*L[1] + 3*L[2]
    # -I acts on the weight vector w by (-1)^(sum of the "box content"), i.e. (-1)^(sum n_i)
    # and sum n_i = boxes for every weight of the irrep. Verify that sum n_i is constant:
    sums = set()
    for w, mult in A3(*L).weight_multiplicities().items():
        n = [ZZ(w[i] + QQ(boxes)/4) for i in range(4)]
        sums.add(sum(n))
    ok = (sums == {boxes})
    if not ok: bad += 1
    print("   %-10s %-8d %-10d %-12s %s" % (str(L), boxes, boxes % 4, (-1)**boxes,
          "(-1)^%d = %+d  %s" % (boxes, (-1)**boxes, "OK" if ok else "*** sum n_i NOT constant ***")))
print("\n   irreps where sum(n_i) is not constant:", bad)

print("\n4) The alphabet identity IS multiplication by the central element:")
R.<t> = LaurentPolynomialRing(QQ)
S  = [R(1), t, R(-1), t**-1]          # the alphabet, as the orbifold hands it to us
Sm = [R(1), -t, R(-1), -t**-1]        # the same alphabet at t -> -t  (alpha_2 -> alpha_2 + 1)
negS = [-x for x in S]                # the alphabet acted on by -I
print("   {1,-t,-1,-1/t} as a multiset :", sorted(Sm, key=str))
print("   -1 * {1,t,-1,1/t}            :", sorted(negS, key=str))
print("   equal as multisets           :", sorted(Sm, key=str) == sorted(negS, key=str))
print("\n   => t -> -t  (a half period in alpha_2) and the central element -I act identically")
print("      on the weight system, so the response is (-1)^(a+2b+3c): the centre charge mod 2.")
